// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category_keywords.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createKeyword = `-- name: CreateKeyword :one
INSERT INTO category_keywords (category_id, keyword, keyword_type)
VALUES ($1, LOWER($2), $3)
RETURNING id, uuid, category_id, keyword, keyword_type, created_at, updated_at, deleted_at
`

type CreateKeywordParams struct {
	CategoryID  int32       `json:"category_id"`
	Lower       string      `json:"lower"`
	KeywordType pgtype.Text `json:"keyword_type"`
}

func (q *Queries) CreateKeyword(ctx context.Context, arg CreateKeywordParams) (CategoryKeyword, error) {
	row := q.db.QueryRow(ctx, createKeyword, arg.CategoryID, arg.Lower, arg.KeywordType)
	var i CategoryKeyword
	err := row.Scan(
		&i.ID,
		&i.UUID,
		&i.CategoryID,
		&i.Keyword,
		&i.KeywordType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteKeyword = `-- name: DeleteKeyword :exec
UPDATE category_keywords
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) DeleteKeyword(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteKeyword, id)
	return err
}

const getKeywordByID = `-- name: GetKeywordByID :one
SELECT id, uuid, category_id, keyword, keyword_type, created_at, updated_at, deleted_at FROM category_keywords
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetKeywordByID(ctx context.Context, id int32) (CategoryKeyword, error) {
	row := q.db.QueryRow(ctx, getKeywordByID, id)
	var i CategoryKeyword
	err := row.Scan(
		&i.ID,
		&i.UUID,
		&i.CategoryID,
		&i.Keyword,
		&i.KeywordType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listKeywordsByCategoryID = `-- name: ListKeywordsByCategoryID :many
SELECT id, uuid, category_id, keyword, keyword_type, created_at, updated_at, deleted_at FROM category_keywords
WHERE category_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListKeywordsByCategoryID(ctx context.Context, categoryID int32) ([]CategoryKeyword, error) {
	rows, err := q.db.Query(ctx, listKeywordsByCategoryID, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategoryKeyword
	for rows.Next() {
		var i CategoryKeyword
		if err := rows.Scan(
			&i.ID,
			&i.UUID,
			&i.CategoryID,
			&i.Keyword,
			&i.KeywordType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchKeyword = `-- name: SearchKeyword :many
SELECT ck.id, ck.uuid, ck.category_id, ck.keyword, ck.keyword_type, ck.created_at, ck.updated_at, ck.deleted_at FROM category_keywords ck
JOIN categories c ON ck.category_id = c.id
WHERE ck.keyword LIKE CONCAT('%', LOWER($1), '%')
  AND ck.deleted_at IS NULL
  AND c.deleted_at IS NULL
  AND c.user_id = $2
`

type SearchKeywordParams struct {
	Lower  string `json:"lower"`
	UserID int32  `json:"user_id"`
}

func (q *Queries) SearchKeyword(ctx context.Context, arg SearchKeywordParams) ([]CategoryKeyword, error) {
	rows, err := q.db.Query(ctx, searchKeyword, arg.Lower, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategoryKeyword
	for rows.Next() {
		var i CategoryKeyword
		if err := rows.Scan(
			&i.ID,
			&i.UUID,
			&i.CategoryID,
			&i.Keyword,
			&i.KeywordType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateKeyword = `-- name: UpdateKeyword :one
UPDATE category_keywords
SET keyword = COALESCE($1, keyword),
    keyword_type = COALESCE($2, keyword_type),
    updated_at = NOW()
WHERE id = $3
  AND deleted_at IS NULL
RETURNING id, uuid, category_id, keyword, keyword_type, created_at, updated_at, deleted_at
`

type UpdateKeywordParams struct {
	Keyword     pgtype.Text `json:"keyword"`
	KeywordType pgtype.Text `json:"keyword_type"`
	ID          int32       `json:"id"`
}

func (q *Queries) UpdateKeyword(ctx context.Context, arg UpdateKeywordParams) (CategoryKeyword, error) {
	row := q.db.QueryRow(ctx, updateKeyword, arg.Keyword, arg.KeywordType, arg.ID)
	var i CategoryKeyword
	err := row.Scan(
		&i.ID,
		&i.UUID,
		&i.CategoryID,
		&i.Keyword,
		&i.KeywordType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
