// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (user_id, parent_id, name, color_code, sort_order)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, uuid, user_id, parent_id, name, color_code, is_active, sort_order, created_at, updated_at
`

type CreateCategoryParams struct {
	UserID    int32       `json:"user_id"`
	ParentID  pgtype.Int4 `json:"parent_id"`
	Name      string      `json:"name"`
	ColorCode string      `json:"color_code"`
	SortOrder int32       `json:"sort_order"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.UserID,
		arg.ParentID,
		arg.Name,
		arg.ColorCode,
		arg.SortOrder,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UUID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.ColorCode,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, uuid, user_id, parent_id, name, color_code, is_active, sort_order, created_at, updated_at FROM categories
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id int32) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UUID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.ColorCode,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryByUUID = `-- name: GetCategoryByUUID :one
SELECT id, uuid, user_id, parent_id, name, color_code, is_active, sort_order, created_at, updated_at FROM categories
WHERE uuid = $1 LIMIT 1
`

func (q *Queries) GetCategoryByUUID(ctx context.Context, argUuid uuid.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByUUID, argUuid)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UUID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.ColorCode,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategoriesByUserId = `-- name: ListCategoriesByUserId :many
SELECT id, uuid, user_id, parent_id, name, color_code, is_active, sort_order, created_at, updated_at FROM categories
WHERE user_id = $1 AND is_active = TRUE
ORDER BY sort_order ASC
`

func (q *Queries) ListCategoriesByUserId(ctx context.Context, userID int32) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoriesByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UUID,
			&i.UserID,
			&i.ParentID,
			&i.Name,
			&i.ColorCode,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
