// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID        int32              `json:"id"`
	UUID      uuid.UUID          `json:"uuid"`
	UserID    int32              `json:"user_id"`
	ParentID  pgtype.Int4        `json:"parent_id"`
	Name      string             `json:"name"`
	ColorCode string             `json:"color_code"`
	IsActive  bool               `json:"is_active"`
	SortOrder int32              `json:"sort_order"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type RawMessage struct {
	ID           int32              `json:"id"`
	UserID       int32              `json:"user_id"`
	MessageText  string             `json:"message_text"`
	TimeRecordID pgtype.Int4        `json:"time_record_id"`
	Processed    bool               `json:"processed"`
	ProcessedAt  pgtype.Timestamptz `json:"processed_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type StatisticsConfig struct {
	ID          int32              `json:"id"`
	UserID      int32              `json:"user_id"`
	ConfigName  string             `json:"config_name"`
	CategoryIds []int32            `json:"category_ids"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type TimeRecord struct {
	ID              int32              `json:"id"`
	UUID            uuid.UUID          `json:"uuid"`
	UserID          int32              `json:"user_id"`
	CategoryID      pgtype.Int4        `json:"category_id"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	EndTime         pgtype.Timestamptz `json:"end_time"`
	DurationMinutes int32              `json:"duration_minutes"`
	Note            pgtype.Text        `json:"note"`
	Source          string             `json:"source"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           int32              `json:"id"`
	UUID         uuid.UUID          `json:"uuid"`
	Email        string             `json:"email"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
