// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: raw_messages.sql

package store

import (
	"context"
)

const createRawMessage = `-- name: CreateRawMessage :one
INSERT INTO raw_messages (user_id, message_text)
VALUES ($1, $2)
RETURNING id, user_id, message_text, time_record_id, processed, processed_at, created_at, updated_at
`

type CreateRawMessageParams struct {
	UserID      int32  `json:"user_id"`
	MessageText string `json:"message_text"`
}

func (q *Queries) CreateRawMessage(ctx context.Context, arg CreateRawMessageParams) (RawMessage, error) {
	row := q.db.QueryRowContext(ctx, createRawMessage, arg.UserID, arg.MessageText)
	var i RawMessage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MessageText,
		&i.TimeRecordID,
		&i.Processed,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
