// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: records.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkOverlap = `-- name: CheckOverlap :one
SELECT EXISTS (
    SELECT 1 FROM time_records
    WHERE user_id = $1
    AND (start_time, end_time) OVERLAPS ($2, $3)
)
`

type CheckOverlapParams struct {
	UserID     int32       `json:"user_id"`
	Overlaps   interface{} `json:"overlaps"`
	Overlaps_2 interface{} `json:"overlaps_2"`
}

// 检查时间是否重叠
func (q *Queries) CheckOverlap(ctx context.Context, arg CheckOverlapParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkOverlap, arg.UserID, arg.Overlaps, arg.Overlaps_2)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countRecords = `-- name: CountRecords :one
SELECT COUNT(*)
FROM time_records tr
WHERE tr.user_id = $1
AND tr.start_time >= $2
AND tr.start_time < $3
`

type CountRecordsParams struct {
	UserID      int32              `json:"user_id"`
	StartTime   pgtype.Timestamptz `json:"start_time"`
	StartTime_2 pgtype.Timestamptz `json:"start_time_2"`
}

// 统计记录数量
func (q *Queries) CountRecords(ctx context.Context, arg CountRecordsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecords, arg.UserID, arg.StartTime, arg.StartTime_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRecord = `-- name: CreateRecord :one
INSERT INTO time_records (
    user_id, category_id, start_time, end_time, duration_minutes, note, source
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, uuid, user_id, category_id, start_time, end_time, duration_minutes, note, source, created_at, updated_at
`

type CreateRecordParams struct {
	UserID          int32              `json:"user_id"`
	CategoryID      pgtype.Int4        `json:"category_id"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	EndTime         pgtype.Timestamptz `json:"end_time"`
	DurationMinutes int32              `json:"duration_minutes"`
	Note            pgtype.Text        `json:"note"`
	Source          string             `json:"source"`
}

func (q *Queries) CreateRecord(ctx context.Context, arg CreateRecordParams) (TimeRecord, error) {
	row := q.db.QueryRow(ctx, createRecord,
		arg.UserID,
		arg.CategoryID,
		arg.StartTime,
		arg.EndTime,
		arg.DurationMinutes,
		arg.Note,
		arg.Source,
	)
	var i TimeRecord
	err := row.Scan(
		&i.ID,
		&i.UUID,
		&i.UserID,
		&i.CategoryID,
		&i.StartTime,
		&i.EndTime,
		&i.DurationMinutes,
		&i.Note,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRecord = `-- name: DeleteRecord :exec
DELETE FROM time_records WHERE uuid = $1 AND user_id = $2
`

type DeleteRecordParams struct {
	UUID   uuid.UUID `json:"uuid"`
	UserID int32     `json:"user_id"`
}

// 删除记录
func (q *Queries) DeleteRecord(ctx context.Context, arg DeleteRecordParams) error {
	_, err := q.db.Exec(ctx, deleteRecord, arg.UUID, arg.UserID)
	return err
}

const getDailyRecords = `-- name: GetDailyRecords :many
SELECT id, uuid, user_id, category_id, start_time, end_time, duration_minutes, note, source, created_at, updated_at FROM time_records
WHERE user_id = $1
AND start_time >= $2
AND start_time < $3
ORDER BY start_time ASC
`

type GetDailyRecordsParams struct {
	UserID      int32              `json:"user_id"`
	StartTime   pgtype.Timestamptz `json:"start_time"`
	StartTime_2 pgtype.Timestamptz `json:"start_time_2"`
}

// 获取用户在指定日期范围内的时间记录
func (q *Queries) GetDailyRecords(ctx context.Context, arg GetDailyRecordsParams) ([]TimeRecord, error) {
	rows, err := q.db.Query(ctx, getDailyRecords, arg.UserID, arg.StartTime, arg.StartTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimeRecord
	for rows.Next() {
		var i TimeRecord
		if err := rows.Scan(
			&i.ID,
			&i.UUID,
			&i.UserID,
			&i.CategoryID,
			&i.StartTime,
			&i.EndTime,
			&i.DurationMinutes,
			&i.Note,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecordByUUID = `-- name: GetRecordByUUID :one
SELECT tr.id, tr.uuid, tr.user_id, tr.category_id, tr.start_time, tr.end_time, tr.duration_minutes, tr.note, tr.source, tr.created_at, tr.updated_at, c.uuid as category_uuid
FROM time_records tr
LEFT JOIN categories c ON tr.category_id = c.id
WHERE tr.uuid = $1 AND tr.user_id = $2
`

type GetRecordByUUIDParams struct {
	UUID   uuid.UUID `json:"uuid"`
	UserID int32     `json:"user_id"`
}

type GetRecordByUUIDRow struct {
	ID              int32              `json:"id"`
	UUID            uuid.UUID          `json:"uuid"`
	UserID          int32              `json:"user_id"`
	CategoryID      pgtype.Int4        `json:"category_id"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	EndTime         pgtype.Timestamptz `json:"end_time"`
	DurationMinutes int32              `json:"duration_minutes"`
	Note            pgtype.Text        `json:"note"`
	Source          string             `json:"source"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CategoryUuid    pgtype.UUID        `json:"category_uuid"`
}

// 根据UUID获取单条记录
func (q *Queries) GetRecordByUUID(ctx context.Context, arg GetRecordByUUIDParams) (GetRecordByUUIDRow, error) {
	row := q.db.QueryRow(ctx, getRecordByUUID, arg.UUID, arg.UserID)
	var i GetRecordByUUIDRow
	err := row.Scan(
		&i.ID,
		&i.UUID,
		&i.UserID,
		&i.CategoryID,
		&i.StartTime,
		&i.EndTime,
		&i.DurationMinutes,
		&i.Note,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryUuid,
	)
	return i, err
}

const getRecords = `-- name: GetRecords :many
SELECT tr.id, tr.uuid, tr.user_id, tr.category_id, tr.start_time, tr.end_time, tr.duration_minutes, tr.note, tr.source, tr.created_at, tr.updated_at, c.uuid as category_uuid
FROM time_records tr
LEFT JOIN categories c ON tr.category_id = c.id
WHERE tr.user_id = $1
AND tr.start_time >= $2
AND tr.start_time < $3
ORDER BY tr.start_time DESC
LIMIT $4 OFFSET $5
`

type GetRecordsParams struct {
	UserID      int32              `json:"user_id"`
	StartTime   pgtype.Timestamptz `json:"start_time"`
	StartTime_2 pgtype.Timestamptz `json:"start_time_2"`
	Limit       int32              `json:"limit"`
	Offset      int32              `json:"offset"`
}

type GetRecordsRow struct {
	ID              int32              `json:"id"`
	UUID            uuid.UUID          `json:"uuid"`
	UserID          int32              `json:"user_id"`
	CategoryID      pgtype.Int4        `json:"category_id"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	EndTime         pgtype.Timestamptz `json:"end_time"`
	DurationMinutes int32              `json:"duration_minutes"`
	Note            pgtype.Text        `json:"note"`
	Source          string             `json:"source"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CategoryUuid    pgtype.UUID        `json:"category_uuid"`
}

// 获取记录列表（支持分页和日期过滤）
func (q *Queries) GetRecords(ctx context.Context, arg GetRecordsParams) ([]GetRecordsRow, error) {
	rows, err := q.db.Query(ctx, getRecords,
		arg.UserID,
		arg.StartTime,
		arg.StartTime_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecordsRow
	for rows.Next() {
		var i GetRecordsRow
		if err := rows.Scan(
			&i.ID,
			&i.UUID,
			&i.UserID,
			&i.CategoryID,
			&i.StartTime,
			&i.EndTime,
			&i.DurationMinutes,
			&i.Note,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecord = `-- name: UpdateRecord :one
UPDATE time_records
SET category_id = $2, start_time = $3, end_time = $4, duration_minutes = $5, note = $6, updated_at = NOW()
WHERE uuid = $1 AND user_id = $7
RETURNING id, uuid, user_id, category_id, start_time, end_time, duration_minutes, note, source, created_at, updated_at
`

type UpdateRecordParams struct {
	UUID            uuid.UUID          `json:"uuid"`
	CategoryID      pgtype.Int4        `json:"category_id"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	EndTime         pgtype.Timestamptz `json:"end_time"`
	DurationMinutes int32              `json:"duration_minutes"`
	Note            pgtype.Text        `json:"note"`
	UserID          int32              `json:"user_id"`
}

// 更新记录
func (q *Queries) UpdateRecord(ctx context.Context, arg UpdateRecordParams) (TimeRecord, error) {
	row := q.db.QueryRow(ctx, updateRecord,
		arg.UUID,
		arg.CategoryID,
		arg.StartTime,
		arg.EndTime,
		arg.DurationMinutes,
		arg.Note,
		arg.UserID,
	)
	var i TimeRecord
	err := row.Scan(
		&i.ID,
		&i.UUID,
		&i.UserID,
		&i.CategoryID,
		&i.StartTime,
		&i.EndTime,
		&i.DurationMinutes,
		&i.Note,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
