// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: records.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const checkOverlap = `-- name: CheckOverlap :one
SELECT EXISTS (
    SELECT 1 FROM time_records
    WHERE user_id = $1
    AND (start_time, end_time) OVERLAPS ($2, $3)
)
`

type CheckOverlapParams struct {
	UserID     int32       `json:"user_id"`
	Overlaps   interface{} `json:"overlaps"`
	Overlaps_2 interface{} `json:"overlaps_2"`
}

// 检查时间是否重叠
func (q *Queries) CheckOverlap(ctx context.Context, arg CheckOverlapParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkOverlap, arg.UserID, arg.Overlaps, arg.Overlaps_2)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createRecord = `-- name: CreateRecord :one
INSERT INTO time_records (
    user_id, category_id, start_time, end_time, duration_minutes, note, source
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, user_id, category_id, start_time, end_time, duration_minutes, note, source, created_at, updated_at
`

type CreateRecordParams struct {
	UserID          int32          `json:"user_id"`
	CategoryID      sql.NullInt32  `json:"category_id"`
	StartTime       time.Time      `json:"start_time"`
	EndTime         time.Time      `json:"end_time"`
	DurationMinutes int32          `json:"duration_minutes"`
	Note            sql.NullString `json:"note"`
	Source          string         `json:"source"`
}

func (q *Queries) CreateRecord(ctx context.Context, arg CreateRecordParams) (TimeRecord, error) {
	row := q.db.QueryRowContext(ctx, createRecord,
		arg.UserID,
		arg.CategoryID,
		arg.StartTime,
		arg.EndTime,
		arg.DurationMinutes,
		arg.Note,
		arg.Source,
	)
	var i TimeRecord
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.StartTime,
		&i.EndTime,
		&i.DurationMinutes,
		&i.Note,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDailyRecords = `-- name: GetDailyRecords :many
SELECT id, user_id, category_id, start_time, end_time, duration_minutes, note, source, created_at, updated_at FROM time_records
WHERE user_id = $1 
AND start_time >= $2 
AND start_time < $3
ORDER BY start_time ASC
`

type GetDailyRecordsParams struct {
	UserID      int32     `json:"user_id"`
	StartTime   time.Time `json:"start_time"`
	StartTime_2 time.Time `json:"start_time_2"`
}

// 获取用户在指定日期范围内的时间记录
func (q *Queries) GetDailyRecords(ctx context.Context, arg GetDailyRecordsParams) ([]TimeRecord, error) {
	rows, err := q.db.QueryContext(ctx, getDailyRecords, arg.UserID, arg.StartTime, arg.StartTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimeRecord
	for rows.Next() {
		var i TimeRecord
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.StartTime,
			&i.EndTime,
			&i.DurationMinutes,
			&i.Note,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
